# Generated by Django 4.2.4 on 2023-08-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tags', models.CharField(help_text='write hashtags seperated by comma', max_length=255)),
                ('content', models.TextField(help_text='You can use markdown!')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
